### ISSUE TITLE
Better integration with lutris (Feature)

### ISSUE THREAD

**Issue by pktiuk** [juliagoda/antimicroX#121]
It wuld be cool and convenient to add better integration with [lutris](https://github.com/lutris/lutris) (the most popular game launcher on linux).

For example:
- It could be done by detecting games installed by lutris and by editing their configurations add antimicrox to apps activated (with selected preset) when game is run. - It would be good for games which doesn't support gamepads and we just want to use our own mappings of gamepad buttons to keyboard buttons.
- in simpler cases it could just add to enviromental variables: SDL_GAMECONTROLLERCONFIG describing configured gamepads. - It would be good for games supporting Xbox gamepads, but incompatible with our custom gamepads.

**Comment by juliagoda** [comment]
You said how could be done. Why do you think it would be cool to do that? What exactly improves this combination of these programs? Why it would be more convenient? What are all the prons and cons? Does not the first point coincide with autoprofiles? Sorry, no offence, I just want to know more.

**Comment by pktiuk** [comment]
At first I would like to mention that lutris is the most popular app used for playing and managing games on linux. It is integrated with Steam, GOG, Humble Store and multiple emulators.

> Why do you think it would be cool to do that? Why it would be more convenient? 

- In case of running antimicroX in background when game starts - because it would be convenient for end-users to just configure antimicro once and then just forget about activating it (with right profile) every time when you want to run your game. Moreover not every user is enough good in dealing with shell to setup it.
- In case of using SDL_GAMECONTROLLERCONFIG - copying this config for every game in library can be annoying and repetitive, moreover this setting would be rather the same for every game, because it is just variable that maps our gamepad buttons on regular x360 gamepad.

>Does not the first point coincide with autoprofiles? 

I don't know. What do you mean by autoprofiles?
(Maybe I haven't described first point properly. I have changed it's description to make it clearer)

**Comment by juliagoda** [comment]
> At first I would like to mention that lutris is the most popular app used for playing and managing games on linux. It is integrated with Steam, GOG, Humble Store and multiple emulators.

Sure, I understand it very well, but the fact that a program is commonly known for something does not mean that linking it to another program must make sense. Of course, it doesn't mean that I don't take the idea into account. I have never personally used this program so I would have to look at it first to know how it would be implemented. Another thing is that if lutris is a much bigger program than antimicrox, it is lutris who should be using antimicrox as a sub program. I don't know if they'd agree to that. If they wouldn't agree to such an add-on, I would have to create a fork and change the code just so that someone doesn't have to set up a profile in the settings for this game. Bad deal.

**Comment by pktiuk** [comment]
In solution proposed by myself antimicroX wouldn't be a subprogram, it would just simply edit config files of games saved in lutris
Example file:
```yaml

game:
  exe: /home/pawel/Games/epic-games-store/drive_c/Program Files/Epic Games/Overcooked/Overcooked.exe
  prefix: ~/Games/epic-games-store
  working_dir: ~/Games/epic-games-store/drive_c/Program Files/Epic Games/Overcooked
system:
  env:
    SDL_GAMECONTROLLERCONFIG: 0500000047616d65506164457870000000,GamePadExp,platform:Linux,a:b14,b:b13,x:b15,y:b12,back:b0,start:b3,leftshoulder:b10,rightshoulder:b11,leftstick:b1,rightstick:b2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b8,righttrigger:b9,dpup:b4,dpleft:b7,dpdown:b6,dpright:b5,
  sdl_video_fullscreen: 'off'
wine:
  version: lutris-5.6-2-x86_64
```
adding SDL_GAMECONTROLLERCONFIG is straightforward.
